# Generated by Django 4.0.4 on 2022-05-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
    ]
