# Generated by Django 4.0.4 on 2022-05-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_orgnization'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.orgnization'),
        ),
    ]
