# Generated by Django 4.0.4 on 2022-05-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_client_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='org',
            new_name='orgnization',
        ),
    ]
