# Generated by Django 4.1.2 on 2022-10-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_assignment_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='city',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
