# Generated by Django 4.0.4 on 2022-05-25 21:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address_1',
            field=models.CharField(blank=True, max_length=70, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_2',
            field=models.CharField(blank=True, max_length=70, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=70, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, max_length=70, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='default/default-logo.jpg', upload_to='organization/logo/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, max_length=70, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='organization',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Zip Code'),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(blank=True, max_length=70, verbose_name='Address Line 1')),
                ('address_2', models.CharField(blank=True, max_length=70, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=70, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=70, verbose_name='State/Province')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Zip Code')),
                ('country', models.CharField(blank=True, max_length=70, verbose_name='Country')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('logo', models.ImageField(default='default/default-logo.jpg', upload_to='client/logo/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('youtube', models.CharField(blank=True, max_length=255)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('insta', models.CharField(blank=True, max_length=255)),
                ('tiktok', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.client')),
            ],
            options={
                'verbose_name': 'client profile',
                'verbose_name_plural': 'client profiles',
            },
        ),
    ]
