# Generated by Django 4.0.4 on 2022-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_memberrequest_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrequest',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='memberrequest',
            name='rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
