# Generated by Django 4.1.2 on 2022-10-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_organization_address_1_organization_address_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'clients profile', 'verbose_name_plural': 'clients profiles'},
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website',
        ),
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='logo',
            field=models.ImageField(default='default/default-log.png', upload_to='client/logo/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='default/default-log.png', upload_to='organization/logo/'),
        ),
    ]
