# Generated by Django 4.0.4 on 2022-05-25 20:50

import account.permissions.models
import account.user.models.path
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=(models.Model, account.permissions.models.PermissionsMixinFacade),
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this attr should be treated as active. Unselect this instead of deleting object.', verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='UserServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this attr should be treated as active. Unselect this instead of deleting object.', verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('address_1', models.CharField(blank=True, max_length=70, verbose_name='Address Line 1')),
                ('address_2', models.CharField(blank=True, max_length=70, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=70, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=70, verbose_name='State/Province')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Zip Code')),
                ('country', models.CharField(blank=True, max_length=70, verbose_name='Country')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('is_visitor', models.BooleanField(default=True)),
                ('is_content_creator', models.BooleanField(default=False)),
                ('is_expert', models.BooleanField(default=False)),
                ('image', models.ImageField(default='profile/default-profile.jpg', help_text='If user is not set the profile image. The system automatically add default image for user.', upload_to=account.user.models.path.file_path, verbose_name='profile image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
