# Generated by Django 4.0.4 on 2022-05-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='The tenants this user belongs to.', related_name='user_set', to='membership.client', verbose_name='tenants'),
        ),
    ]
