# Generated by Django 3.2.15 on 2022-10-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='The tenants this user belongs to.', related_name='user_set', to='membership.Client', verbose_name='tenants'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_interest',
            field=models.ManyToManyField(blank=True, related_name='interest', to='account.UserInterest'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_services',
            field=models.ManyToManyField(blank=True, related_name='services', to='account.UserServices'),
        ),
    ]
