# Generated by Django 4.0.4 on 2022-05-25 21:55

import account.user.models.path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default/default-profile.jpg', help_text='If user is not set the profile image. The system automatically add default image for user.', upload_to=account.user.models.path.file_path, verbose_name='profile image'),
        ),
    ]
