# Generated by Django 3.2.15 on 2022-10-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone Number'),
        ),
        migrations.CreateModel(
            name='UserSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facebook', models.URLField(blank=True, max_length=100, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, max_length=100, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, max_length=100, verbose_name='Linkedin')),
                ('instagram', models.URLField(blank=True, max_length=100, verbose_name='instagram')),
                ('youtube', models.URLField(blank=True, max_length=100, verbose_name='Youtube')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='account.user')),
            ],
            options={
                'verbose_name': 'user social media',
                'verbose_name_plural': 'user social medias',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.CharField(max_length=100, verbose_name='Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='account.user')),
            ],
            options={
                'verbose_name': 'user skill',
                'verbose_name_plural': 'user skills',
            },
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('orgnization', models.CharField(max_length=100, verbose_name='Organization')),
                ('join_date', models.DateField(verbose_name='Join Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('currently_working', models.BooleanField(default=False, help_text='If user is currently working in this organization.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='account.user')),
            ],
            options={
                'verbose_name': 'user experience',
                'verbose_name_plural': 'user experiences',
            },
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.CharField(max_length=100, verbose_name='Degree')),
                ('institute', models.CharField(max_length=100, verbose_name='Institute')),
                ('join_date', models.DateField(verbose_name='Join Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('currently_studying', models.BooleanField(default=False, help_text='If user is currently studying in this institute.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='account.user')),
            ],
            options={
                'verbose_name': 'user education',
                'verbose_name_plural': 'user educations',
            },
        ),
    ]
