# Generated by Django 4.1.2 on 2022-10-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20221013_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usereducation',
            old_name='end_date',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='usereducation',
            old_name='join_date',
            new_name='start_from',
        ),
    ]
