# Generated by Django 4.0.4 on 2022-05-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantpermissions',
            old_name='profile',
            new_name='user',
        ),
    ]
